os: linux
language: node_js
node_js:
  - "lts/*"
install:
  - pushd docs
  - npm ci
  - popd
  - pushd package
  - npm ci
  - popd
cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: tests
      name: Linting
      script:
        - pushd package
        - npm run lint
        - popd
        - pushd docs
        - npm run lint
        - popd

    - stage: tests
      name: Unit test
      script:
        - cd package
        - npm run test:unit

    - stage: tests
      name: Backstop test
      before_script:
        - cd docs
        - npm run serve &
      script:
        - docker run --rm -it --network="host" --mount type=bind,source="/home/travis/build/xLasercut/nhsuk-frontend-vue/package",target=/src backstopjs/backstopjs:4.1.9 test --config=tests/backstop/config.js --moby --testhost=http://127.0.0.1:8080

    - stage: tests
      name: Build test
      script:
        - pushd package
        - npm run build
        - popd
        - pushd docs
        - npm run build:gh
        - popd

    - stage: deploy
      name: Deploy docs
      if: tag IS present
      script:
        - pushd docs
        - npm run build:gh
        - popd
      deploy:
        provider: pages
        local_dir: ./docs/dist
        keep_history: true
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true

    - stage: deploy
      name: Deploy to npm
      if: tag IS present
      script:
        - pushd package
        - npm run build
        - popd
      before_deploy:
        - cd package
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_KEY
        skip_cleanup: true
        on:
          tags: true
