language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
  services:
    - docker
  stages:
    - tests
    - name: master
      if: branch = master
    - name: tag
      if: tag IS present

jobs:
  include:
    - stage: tests
      name: Linting
      script: npm run lint

    - stage: tests
      name: Unit
      script: npm run test:unit

    - stage: tests
      name: Backstop
      before_script:
        - npm run serve &
      script:
        - npm run backstop:test