language: node_js
node_js:
  - "lts/*"
install:
  - pushd docs
  - npm ci
  - popd
  - pushd package
  - npm ci
  - popd
cache:
  directories:
    - ~/.npm
    - ~/.cache
  services:
    - docker
  stages:
    - tests
    - deploy

jobs:
  include:
    #- stage: tests
    #  name: Linting
    #  script: npm run lint

    #- stage: tests
    #  name: Unit test
    #  script: npm run test:unit

    #- stage: tests
    #  name: Backstop test
    #  before_script:
    #    - npm run serve &
    #  script:
    #    - docker run --rm -it --network="host" --mount type=bind,source="/home/travis/build/xLasercut/nhsuk-frontend-vue/package",target=/src backstopjs/backstopjs:4.1.9 test --config=tests/backstop/config.js --moby --testhost=http://127.0.0.1:8080

    #- stage: tests
    #  name: Build test
    #  script: npm run build

    - stage: deploy
      name: Deploy docs
      script:
        - cd docs
        - npm run build:gh
      deploy:
        skip_cleanup: true
        provider: pages
        local-dir: ./dist
        keep-history: true
        github-token: $GITHUB_TOKEN

    - stage: deploy
      name: Deploy to npm
      if: tag IS present
      script:
        - cd package
        - npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_KEY
        skip_cleanup: true
        on:
          tags: true
