language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
  services:
    - docker
  stages:
    - tests
    - deploy

jobs:
  include:
    - stage: tests
      name: Linting
      script: npm run lint

    - stage: tests
      name: Unit
      script: npm run test:unit

    - stage: tests
      name: Backstop
      before_script:
        - npm run serve &
      script:
        - docker run --rm -it --network="host" --mount type=bind,source="/home/travis/build/xLasercut/nhsuk-frontend-vue",target=/src backstopjs/backstopjs:4.1.9 test --config=tests/backstop/config.js --moby --testhost=http://127.0.0.1:8080

    - stage: deploy
      if: tag IS present
      name: Deploy docs
      script:
        - npm run deploy:gh
      deploy:
        skip_cleanup: true
        provider: pages
        local-dir: ./dist_docs
        keep-history: true
        github-token: $GITHUB_TOKEN
        on:
          branch: master
