name: CI Build

on:
  push:
    branches:
      - dev
      - master


jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: ./package
    - run: npm run lint
      working-directory: ./package


  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: ./package
    - run: npm run test:unit
      working-directory: ./package

