name: CI Build

on:
  push:
    branches:
      - dev
      - master


jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install packages and run test
        working-directory: ./package
        run: npm ci
        run: npm run lint


  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install packages and run test
        working-directory: ./package
        run: npm ci
        run: npm run test:unit

