name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          pushd docs
          npm ci
          popd
          pushd package
          npm ci
          popd

      - name: Run linting
        run: |
          pushd package
          npm run lint
          popd
          pushd docs
          npm run lint
          popd

      - name: Run unit tests
        run: |
          pushd package
          npm run test:unit
          popd

      - name: Run build tests
        run: |
          pushd package
          npm run build
          popd
          pushd docs
          npm run build:gh
          popd

      - name: Run backstop tests
        run: |
          pushd docs
          npm run serve &
          popd
          pushd package
          npm run test:backstop
          popd

      - name: Build docs
        run: |
          pushd docs
          npm run build:gh
          popd

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/dist

      - name: Publish npm package
        run: |
          cd package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
